"""
Backtesting package.

This package provides a full offline backtesting pipeline for the trading system:

- historical data downloading/loading;
- deterministic market replay;
- simulated execution;
- simulated position accounting;
- cost models;
- performance metrics;
- model analytics;
- report building;
- strategy testing;
- walk-forward testing;
- parameter optimization.

The backtesting package should preserve the production event flow:

    market.* -> data -> analytics -> strategy -> risk -> execution simulator -> position simulator

Backtesting must not bypass RiskManager or call live execution services.
"""

from __future__ import annotations

# ============================================================================
# Enums
# ============================================================================

from .enums import (
    BacktestArtifactType,
    BacktestDataType,
    BacktestEventType,
    BacktestMode,
    BacktestStatus,
    BacktestWarningLevel,
    CandleExecutionPath,
    CommissionModel,
    DataGapPolicy,
    DataValidationLevel,
    FillModel,
    FundingSimulationMode,
    HistoricalDataFormat,
    LatencyModel,
    LiquidityModel,
    MetricAggregation,
    OptimizationDirection,
    OptimizationMethod,
    OptimizationMetric,
    OrderRejectionReason,
    PnLAccountingMode,
    PositionAccountingMode,
    ReplayEventPriority,
    ReplayMode,
    ReplayOrdering,
    ReplaySpeed,
    ReportFormat,
    ReportSection,
    SignalOutcome,
    SimulatedOrderStatus,
    SimulatedPositionStatus,
    TradeOutcome,
    WalkForwardMode,
    WalkForwardWindowType,
    WarmupPolicy,
)

# ============================================================================
# Exceptions
# ============================================================================

from .exceptions import (
    BacktestComponentError,
    BacktestConfigurationError,
    BacktestDataError,
    BacktestDependencyError,
    BacktestError,
    BacktestLifecycleError,
    BacktestStateError,
    BacktestTimeError,
    BacktestClockError,
    BacktestClockNotInitializedError,
    BacktestTimeRangeError,
    BacktestTimeTravelError,
    BacktestResultCollectionError,
    BorrowCostCalculationError,
    CommissionCalculationError,
    CostModelError,
    DataAlignmentError,
    DataGapError,
    DataLoadError,
    DataLoaderError,
    DataNormalizationError,
    DataValidationError,
    DatasetIntegrityError,
    DrawdownCalculationError,
    EmptyDatasetError,
    EquityCalculationError,
    EquityCurveError,
    ExecutionPipelineError,
    ExecutionSimulationError,
    ExecutionSimulatorNotReadyError,
    FeatureAnalyticsError,
    FillModelError,
    FundingCostCalculationError,
    HistoricalDataDownloadError,
    HistoricalDataFormatError,
    HistoricalDataGapError,
    HistoricalDataNotFoundError,
    HistoricalDataRangeError,
    HistoricalDataSchemaError,
    HistoricalDataStorageError,
    HistoricalDataValidationError,
    InvalidCostModelInputError,
    LatencySimulationError,
    LiquidationPriceCalculationError,
    LiquidationSimulationError,
    LiquiditySimulationError,
    MarginCalculationError,
    MarketReplayAlreadyRunningError,
    MarketReplayError,
    MarketReplayNotPreparedError,
    MarketReplayPausedError,
    MarketReplayStoppedError,
    MetricInputError,
    ModelAnalyticsError,
    OptimizationConfigurationError,
    OptimizationError,
    OptimizationMetricError,
    OptimizationParameterError,
    OptimizationResultError,
    OptimizationRunError,
    OverfittingDetectionError,
    PerformanceCalculationError,
    PnLCalculationError,
    PositionAccountingError,
    PositionPipelineError,
    PositionSimulationError,
    PositionSimulatorNotReadyError,
    ProtectiveOrderSimulationError,
    RatioCalculationError,
    RegimeAnalyticsError,
    ReplayEmitError,
    ReplayEventError,
    ReplayOrderingError,
    ReplaySeekError,
    ReportArtifactError,
    ReportBuildError,
    ReportFormatError,
    ReportSectionError,
    RiskPipelineError,
    SignalAttributionError,
    SimulatedExchangeError,
    SimulatedOrderCancelError,
    SimulatedOrderError,
    SimulatedOrderFillError,
    SimulatedOrderNotFoundError,
    SimulatedOrderRejectedError,
    SimulatedOrderStateError,
    SimulatedOrderValidationError,
    SimulatedPositionError,
    SimulatedPositionNotFoundError,
    SimulatedPositionStateError,
    SimulatedPositionValidationError,
    SlippageCalculationError,
    SpreadCostCalculationError,
    StrategyAttributionError,
    StrategyBacktestRunError,
    StrategyRegistryEmptyError,
    StrategySelectionError,
    StrategySignalCollectionError,
    StrategyTestError,
    TradeStatsCalculationError,
    UnsupportedDataTypeError,
    WalkForwardAggregationError,
    WalkForwardConfigurationError,
    WalkForwardError,
    WalkForwardRunError,
    WalkForwardSplitError,
    wrap_backtest_error,
)

# ============================================================================
# Configs
# ============================================================================

from .config import (
    BacktestConfig,
    BacktestTimeConfig,
    CostModelConfig,
    DataLoaderConfig,
    ExecutionSimulatorConfig,
    HistoryDownloaderConfig,
    MarketReplayConfig,
    ModelAnalyticsConfig,
    OptimizerConfig,
    PerformanceMetricsConfig,
    PositionSimulatorConfig,
    ReportBuilderConfig,
    StrategyTesterConfig,
    WalkForwardConfig,
)

# ============================================================================
# Models
# ============================================================================

from .models import (
    BacktestArtifact,
    BacktestDataSource,
    BacktestDataset,
    BacktestDatasetInfo,
    BacktestEvent,
    BacktestInstrument,
    BacktestModelAnalytics,
    BacktestPeriod,
    BacktestReport,
    BacktestResult,
    BacktestRiskDecisionRecord,
    BacktestSignalRecord,
    BacktestWarning,
    DrawdownPeriod,
    ExecutionStatsSnapshot,
    HistoricalCandle,
    HistoricalFundingRecord,
    HistoricalLiquidationRecord,
    HistoricalOpenInterestRecord,
    HistoricalOrderBookLevel,
    HistoricalOrderBookSnapshot,
    HistoricalTrade,
    OptimizationParameter,
    OptimizationResult,
    OptimizationTrialResult,
    PerformanceSummary,
    PortfolioBacktestResult,
    RegimePerformanceStats,
    ReplayEventBatch,
    RiskStats,
    SerializableMixin,
    SignalQualityStats,
    SimulatedBalance,
    SimulatedEquityPoint,
    SimulatedFill,
    SimulatedOrder,
    SimulatedPosition,
    SimulatedTrade,
    SimulationModelSnapshot,
    StrategyAttribution,
    StrategyBacktestResult,
    SymbolBacktestResult,
    TradeStats,
    TradingCostBreakdown,
    WalkForwardIterationResult,
    WalkForwardResult,
    WalkForwardWindow,
    datetime_from_ms,
    ensure_aware_utc,
    new_id,
    safe_div,
    timestamp_ms,
    utcnow,
)

# ============================================================================
# Time
# ============================================================================

from .backtest_time import (
    BacktestClock,
    BacktestScheduledJob,
    BacktestTimeProvider,
    BacktestTimeSnapshot,
    SchedulerJobCallback,
    build_backtest_clock,
)

# ============================================================================
# History downloader / data loader / replay
# ============================================================================

from .data_loader import (
    DataFileRef,
    DataLoader,
    LoadedDataBundle,
    load_backtest_bundle,
    load_backtest_dataset,
)



# ============================================================================
# Cost models
# ============================================================================

from .cost_models import (
    BorrowCostCalculator,
    CommissionCalculator,
    CommissionInput,
    FundingCostCalculator,
    FundingInput,
    LiquidationInput,
    LiquidationPriceCalculator,
    SlippageCalculator,
    SlippageInput,
    SpreadCostCalculator,
    TradeCostInput,
    TradingCostModel,
    calculate_r_multiple,
    calculate_return_pct,
    calculate_slippage_bps,
    estimate_holding_seconds,
    normalize_cost_timestamp,
    split_funding_cashflow,
)

# ============================================================================
# Execution / position simulation
# ============================================================================

from .execution_simulator import (
    ExecutionMarketState,
    ExecutionSimulator,
    ExecutionSimulatorStats,
    SimulatedOrderRequest,
)

from .position_simulator import (
    PositionMarketState,
    PositionSimulator,
    PositionSimulatorStats,
)

# ============================================================================
# Metrics / analytics / reports
# ============================================================================

from .performance_metrics import (
    CostStatsCalculator,
    DrawdownCalculator,
    ExecutionStatsCalculator,
    MetricsInput,
    PerformanceMetrics,
    RatioCalculator,
    ReturnsSeries,
    RiskStatsCalculator,
    TradeStatsCalculator,
    build_metrics_input_from_components,
    calculate_expectancy,
    calculate_max_drawdown_pct,
    calculate_profit_factor,
    calculate_win_rate,
)

from .model_analytics import (
    BacktestModelAnalyticsEngine,
    ExecutionQualityAnalytics,
    ExecutionQualityAnalyzer,
    FeatureImportanceAnalyzer,
    ModelAnalytics,
    ModelAnalyticsInput,
    RegimePerformanceAnalyzer,
    RiskDecisionAnalytics,
    RiskDecisionAnalyzer,
    SignalAttributionRecord,
    SignalQualityAnalyzer,
    StrategyAttributionAnalyzer,
    find_underperforming_strategies,
    rank_strategies_by_profit,
    rank_strategies_by_profit_factor,
    summarize_model_analytics,
)

from .report_builder import (
    ReportBuilder,
    build_markdown_report,
    export_backtest_report,
)

# ============================================================================
# Strategy tester / walk-forward / optimizer
# ============================================================================

from .strategy_tester import (
    BacktestCollectors,
    BacktestComponentBundle,
    StrategyTester,

)

from .walk_forward import (
    OptimizerFactory,
    StrategyTesterFactory as WalkForwardStrategyTesterFactory,
    WalkForwardRunStats,
    WalkForwardRunner,
    WalkForwardSplit,
    run_walk_forward,
    run_walk_forward_sync,
)

from .optimizer import (
    OptimizerRunStats,
    ParameterCandidate,
    StrategyOptimizer,
    StrategyTesterFactory as OptimizerStrategyTesterFactory,
    TrialCallback,
    run_optimization,
    run_optimization_sync,
)


__all__ = [
    # Enums
    "BacktestArtifactType",
    "BacktestDataType",
    "BacktestEventType",
    "BacktestMode",
    "BacktestStatus",
    "BacktestWarningLevel",
    "CandleExecutionPath",
    "CommissionModel",
    "DataGapPolicy",
    "DataValidationLevel",
    "FillModel",
    "FundingSimulationMode",
    "HistoricalDataFormat",
    "LatencyModel",
    "LiquidityModel",
    "MetricAggregation",
    "OptimizationDirection",
    "OptimizationMethod",
    "OptimizationMetric",
    "OrderRejectionReason",
    "PnLAccountingMode",
    "PositionAccountingMode",
    "ReplayEventPriority",
    "ReplayMode",
    "ReplayOrdering",
    "ReplaySpeed",
    "ReportFormat",
    "ReportSection",
    "SignalOutcome",
    "SimulatedOrderStatus",
    "SimulatedPositionStatus",
    "TradeOutcome",
    "WalkForwardMode",
    "WalkForwardWindowType",
    "WarmupPolicy",

    # Exceptions
    "BacktestError",
    "BacktestConfigurationError",
    "BacktestDependencyError",
    "BacktestComponentError",
    "BacktestStateError",
    "BacktestLifecycleError",
    "BacktestDataError",
    "HistoricalDataNotFoundError",
    "HistoricalDataDownloadError",
    "HistoricalDataStorageError",
    "HistoricalDataFormatError",
    "HistoricalDataSchemaError",
    "HistoricalDataValidationError",
    "HistoricalDataGapError",
    "HistoricalDataRangeError",
    "DataAlignmentError",
    "DataLoaderError",
    "EmptyDatasetError",
    "DatasetIntegrityError",
    "DataLoadError",
    "DataValidationError",
    "DataNormalizationError",
    "DataGapError",
    "UnsupportedDataTypeError",
    "BacktestTimeError",
    "BacktestClockError",
    "BacktestClockNotInitializedError",
    "BacktestTimeRangeError",
    "BacktestTimeTravelError",
    "MarketReplayError",
    "MarketReplayNotPreparedError",
    "MarketReplayAlreadyRunningError",
    "MarketReplayStoppedError",
    "MarketReplayPausedError",
    "ReplayEventError",
    "ReplayOrderingError",
    "ReplayEmitError",
    "ReplaySeekError",
    "CostModelError",
    "CommissionCalculationError",
    "SlippageCalculationError",
    "SpreadCostCalculationError",
    "FundingCostCalculationError",
    "BorrowCostCalculationError",
    "LiquidationPriceCalculationError",
    "InvalidCostModelInputError",
    "ExecutionSimulationError",
    "ExecutionSimulatorNotReadyError",
    "SimulatedOrderError",
    "SimulatedOrderValidationError",
    "SimulatedOrderRejectedError",
    "SimulatedOrderNotFoundError",
    "SimulatedOrderStateError",
    "SimulatedOrderFillError",
    "SimulatedOrderCancelError",
    "FillModelError",
    "LiquiditySimulationError",
    "LatencySimulationError",
    "SimulatedExchangeError",
    "PositionSimulationError",
    "PositionSimulatorNotReadyError",
    "SimulatedPositionError",
    "SimulatedPositionNotFoundError",
    "SimulatedPositionValidationError",
    "SimulatedPositionStateError",
    "PositionAccountingError",
    "PnLCalculationError",
    "MarginCalculationError",
    "EquityCalculationError",
    "LiquidationSimulationError",
    "ProtectiveOrderSimulationError",
    "StrategyTestError",
    "StrategySelectionError",
    "StrategyRegistryEmptyError",
    "StrategyBacktestRunError",
    "StrategySignalCollectionError",
    "RiskPipelineError",
    "ExecutionPipelineError",
    "PositionPipelineError",
    "BacktestResultCollectionError",
    "PerformanceCalculationError",
    "MetricInputError",
    "EquityCurveError",
    "DrawdownCalculationError",
    "RatioCalculationError",
    "TradeStatsCalculationError",
    "ModelAnalyticsError",
    "SignalAttributionError",
    "StrategyAttributionError",
    "RegimeAnalyticsError",
    "FeatureAnalyticsError",
    "ReportBuildError",
    "ReportFormatError",
    "ReportSectionError",
    "ReportArtifactError",
    "WalkForwardError",
    "WalkForwardConfigurationError",
    "WalkForwardSplitError",
    "WalkForwardRunError",
    "WalkForwardAggregationError",
    "OptimizationError",
    "OptimizationConfigurationError",
    "OptimizationParameterError",
    "OptimizationRunError",
    "OptimizationMetricError",
    "OptimizationResultError",
    "OverfittingDetectionError",
    "wrap_backtest_error",

    # Configs
    "BacktestConfig",
    "BacktestTimeConfig",
    "CostModelConfig",
    "DataLoaderConfig",
    "ExecutionSimulatorConfig",
    "HistoryDownloaderConfig",
    "MarketReplayConfig",
    "ModelAnalyticsConfig",
    "OptimizerConfig",
    "PerformanceMetricsConfig",
    "PositionSimulatorConfig",
    "ReportBuilderConfig",
    "StrategyTesterConfig",
    "WalkForwardConfig",

    # Models
    "SerializableMixin",
    "BacktestPeriod",
    "BacktestInstrument",
    "BacktestDataSource",
    "BacktestDatasetInfo",
    "BacktestEvent",
    "ReplayEventBatch",
    "BacktestDataset",
    "HistoricalCandle",
    "HistoricalTrade",
    "HistoricalOrderBookLevel",
    "HistoricalOrderBookSnapshot",
    "HistoricalFundingRecord",
    "HistoricalOpenInterestRecord",
    "HistoricalLiquidationRecord",
    "SimulatedOrder",
    "SimulatedFill",
    "SimulatedPosition",
    "SimulatedTrade",
    "SimulatedBalance",
    "SimulatedEquityPoint",
    "TradingCostBreakdown",
    "BacktestSignalRecord",
    "BacktestRiskDecisionRecord",
    "TradeStats",
    "RiskStats",
    "ExecutionStatsSnapshot",
    "DrawdownPeriod",
    "PerformanceSummary",
    "StrategyBacktestResult",
    "SymbolBacktestResult",
    "PortfolioBacktestResult",
    "SignalQualityStats",
    "StrategyAttribution",
    "RegimePerformanceStats",
    "BacktestModelAnalytics",
    "SimulationModelSnapshot",
    "BacktestWarning",
    "BacktestArtifact",
    "BacktestReport",
    "BacktestResult",
    "WalkForwardWindow",
    "WalkForwardIterationResult",
    "WalkForwardResult",
    "OptimizationParameter",
    "OptimizationTrialResult",
    "OptimizationResult",
    "utcnow",
    "ensure_aware_utc",
    "timestamp_ms",
    "datetime_from_ms",
    "safe_div",
    "new_id",

    # Time
    "SchedulerJobCallback",
    "BacktestScheduledJob",
    "BacktestTimeSnapshot",
    "BacktestClock",
    "BacktestTimeProvider",
    "build_backtest_clock",

    # Downloader / loader / replay
    "DataFileRef",
    "LoadedDataBundle",
    "DataLoader",
    "load_backtest_dataset",
    "load_backtest_bundle",


    # Cost models
    "CommissionInput",
    "SlippageInput",
    "FundingInput",
    "LiquidationInput",
    "TradeCostInput",
    "CommissionCalculator",
    "SlippageCalculator",
    "SpreadCostCalculator",
    "FundingCostCalculator",
    "BorrowCostCalculator",
    "LiquidationPriceCalculator",
    "TradingCostModel",
    "calculate_slippage_bps",
    "calculate_return_pct",
    "calculate_r_multiple",
    "split_funding_cashflow",
    "estimate_holding_seconds",
    "normalize_cost_timestamp",

    # Simulators
    "ExecutionMarketState",
    "ExecutionSimulatorStats",
    "SimulatedOrderRequest",
    "ExecutionSimulator",
    "PositionMarketState",
    "PositionSimulatorStats",
    "PositionSimulator",

    # Metrics / analytics / reports
    "MetricsInput",
    "ReturnsSeries",
    "TradeStatsCalculator",
    "DrawdownCalculator",
    "RatioCalculator",
    "RiskStatsCalculator",
    "ExecutionStatsCalculator",
    "CostStatsCalculator",
    "PerformanceMetrics",
    "calculate_profit_factor",
    "calculate_win_rate",
    "calculate_expectancy",
    "calculate_max_drawdown_pct",
    "build_metrics_input_from_components",
    "ModelAnalyticsInput",
    "SignalAttributionRecord",
    "RiskDecisionAnalytics",
    "ExecutionQualityAnalytics",
    "SignalQualityAnalyzer",
    "StrategyAttributionAnalyzer",
    "RegimePerformanceAnalyzer",
    "FeatureImportanceAnalyzer",
    "RiskDecisionAnalyzer",
    "ExecutionQualityAnalyzer",
    "BacktestModelAnalyticsEngine",
    "ModelAnalytics",
    "rank_strategies_by_profit",
    "rank_strategies_by_profit_factor",
    "find_underperforming_strategies",
    "summarize_model_analytics",
    "ReportBuilder",
    "build_markdown_report",
    "export_backtest_report",

    # Orchestration

    "BacktestComponentBundle",
    "BacktestCollectors",
    "StrategyTester",

    "OptimizerFactory",
    "WalkForwardStrategyTesterFactory",
    "WalkForwardSplit",
    "WalkForwardRunStats",
    "WalkForwardRunner",
    "run_walk_forward",
    "run_walk_forward_sync",
    "OptimizerStrategyTesterFactory",
    "TrialCallback",
    "ParameterCandidate",
    "OptimizerRunStats",
    "StrategyOptimizer",
    "run_optimization",
    "run_optimization_sync",
]