# trading_system/strategy/__init__.py

from __future__ import annotations

from strategy.base import (
    BaseStrategy,
    BaseStrategyComponent,
    ContextAwareStrategyComponent,
    StatefulStrategyComponent,
)
from strategy.config import (
    DEFAULT_ANALYTICS_EVENT_CATEGORY_PREFIXES,
    BuilderConfig,
    ConfidenceConfig,
    ConflictConfig,
    ConfluenceConfig,
    FeatureFreshnessConfig,
    FilterConfig,
    PortfolioCoordinatorConfig,
    PresetConfig,
    RoutingConfig,
    StrategyConfig,
    StrategyDefinitionConfig,
    StrategyRuntimeConfig,
    VotingConfig,
    WeightingConfig,
)
from strategy.enums import (
    ConfidenceGrade,
    ConflictType,
    EntryType,
    ExitType,
    FeatureSource,
    FilterDecision,
    FreshnessStatus,
    MarketRegime,
    PresetMode,
    RiskPayloadField,
    SignalOrigin,
    SignalPriority,
    SignalSide,
    SignalStatus,
    SignalStrength,
    SetupType,
    StrEnum,
    StrategyCategory,
    StrategyExecutionQuality,
    StrategyLiquidityClass,
    StrategyMarginMode,
    StrategyMarketType,
    StrategyOrderIntent,
    StrategyTradeTier,
    Timeframe,
    TriggerType,
)
from strategy.exceptions import (
    BuilderError,
    ConfluenceError,
    FeatureStoreError,
    FilterExecutionError,
    PortfolioCoordinationError,
    SignalNormalizationError,
    SignalRoutingError,
    StrategyConfigError,
    StrategyError,
    StrategyEvaluationError,
    StrategyRegistrationError,
    StrategyStateError,
    UnsupportedStrategyError,
    ValidationError,
)
from strategy.models import (
    ConfirmedSignal,
    ConflictRecord,
    ConfluenceResult,
    CooldownState,
    EntryPlan,
    ExecutionCostPayload,
    ExecutionPlanDraft,
    ExitPlan,
    FeatureSnapshot,
    FilterResult,
    InvalidationPlan,
    PortfolioSnapshot,
    PriceSnapshot,
    RawStrategySignal,
    RegimeSnapshot,
    RiskReadySignalPayload,
    SignalContext,
    SignalEnvelope,
    SignalWindow,
    StrategyContext,
    StrategyEvaluation,
    StrategyMetadata,
    StrategySignal,
    TargetPlan,
    TradeIdea,
    clamp,
    confidence_to_grade,
    confidence_to_strength,
    ensure_aware_utc,
    utcnow,
)
from strategy.presets import (
    ALL_STRATEGY_NAMES,
    HYBRID_STRATEGIES,
    INTRADAY_STRATEGIES,
    LIQUIDITY_REVERSAL_STRATEGIES,
    MEAN_REVERSION_STRATEGIES,
    OPEN_INTEREST_STRATEGIES,
    ORDERFLOW_STRATEGIES,
    PRICE_ACTION_STRATEGIES,
    SCALPING_STRATEGIES,
    SPOOFING_STRATEGIES,
    SPREADS_PRESET_STRATEGIES,
    SPREADS_STRATEGIES,
    STRATEGY_CATALOG,
    SWING_STRATEGIES,
    TREND_STACK_STRATEGIES,
    WHALES_STRATEGIES,
    StrategyCatalogEntry,
    StrategyFactory,
    StrategyNames,
    StrategyPreset,
    StrategyPresetBuilder,
    Timeframes,
    build_default_preset,
    build_default_strategy_config,
    build_default_strategy_registry,
    build_intraday_preset,
    build_liquidity_reversal_preset,
    build_mean_reversion_preset,
    build_preset_by_name,
    build_scalping_preset,
    build_spreads_preset,
    build_swing_preset,
    build_trend_stack_preset,
    catalog_by_category,
    configured_strategy_names,
    enabled_strategy_names,
    validate_strategy_catalog,
)
from strategy.processor import (
    BuildEvaluation,
    ConflictSummary,
    ConfluenceEngine,
    ConfluenceEvaluation,
    CoordinationDecision,
    FilterEvaluation,
    NormalizedPayload,
    PortfolioCoordinator,
    ProcessedSignalBatch,
    RouteDecision,
    SignalBuilder,
    SignalFilterChain,
    SignalNormalizer,
    SignalProcessor,
    SignalRouter,
    SignalScorer,
    VoteSummary,
    WeightedSignal,
)
from strategy.registry import StrategyRegistry
from strategy.state import (
    SignalState,
    StrategyContextStore,
    StrategyCooldownState,
    StrategyMetricsState,
    StrategyRuntimeState,
)


__version__ = "1.0.0"


__all__ = [
    # base
    "BaseStrategy",
    "BaseStrategyComponent",
    "ContextAwareStrategyComponent",
    "StatefulStrategyComponent",

    # config
    "DEFAULT_ANALYTICS_EVENT_CATEGORY_PREFIXES",
    "BuilderConfig",
    "ConfidenceConfig",
    "ConflictConfig",
    "ConfluenceConfig",
    "FeatureFreshnessConfig",
    "FilterConfig",
    "PortfolioCoordinatorConfig",
    "PresetConfig",
    "RoutingConfig",
    "StrategyConfig",
    "StrategyDefinitionConfig",
    "StrategyRuntimeConfig",
    "VotingConfig",
    "WeightingConfig",

    # enums
    "ConfidenceGrade",
    "ConflictType",
    "EntryType",
    "ExitType",
    "FeatureSource",
    "FilterDecision",
    "FreshnessStatus",
    "MarketRegime",
    "PresetMode",
    "RiskPayloadField",
    "SignalOrigin",
    "SignalPriority",
    "SignalSide",
    "SignalStatus",
    "SignalStrength",
    "SetupType",
    "StrEnum",
    "StrategyCategory",
    "StrategyExecutionQuality",
    "StrategyLiquidityClass",
    "StrategyMarginMode",
    "StrategyMarketType",
    "StrategyOrderIntent",
    "StrategyTradeTier",
    "Timeframe",
    "TriggerType",

    # exceptions
    "BuilderError",
    "ConfluenceError",
    "FeatureStoreError",
    "FilterExecutionError",
    "PortfolioCoordinationError",
    "SignalNormalizationError",
    "SignalRoutingError",
    "StrategyConfigError",
    "StrategyError",
    "StrategyEvaluationError",
    "StrategyRegistrationError",
    "StrategyStateError",
    "UnsupportedStrategyError",
    "ValidationError",

    # models
    "ConfirmedSignal",
    "ConflictRecord",
    "ConfluenceResult",
    "CooldownState",
    "EntryPlan",
    "ExecutionCostPayload",
    "ExecutionPlanDraft",
    "ExitPlan",
    "FeatureSnapshot",
    "FilterResult",
    "InvalidationPlan",
    "PortfolioSnapshot",
    "PriceSnapshot",
    "RawStrategySignal",
    "RegimeSnapshot",
    "RiskReadySignalPayload",
    "SignalContext",
    "SignalEnvelope",
    "SignalWindow",
    "StrategyContext",
    "StrategyEvaluation",
    "StrategyMetadata",
    "StrategySignal",
    "TargetPlan",
    "TradeIdea",
    "clamp",
    "confidence_to_grade",
    "confidence_to_strength",
    "ensure_aware_utc",
    "utcnow",

    # processor
    "BuildEvaluation",
    "ConflictSummary",
    "ConfluenceEngine",
    "ConfluenceEvaluation",
    "CoordinationDecision",
    "FilterEvaluation",
    "NormalizedPayload",
    "PortfolioCoordinator",
    "ProcessedSignalBatch",
    "RouteDecision",
    "SignalBuilder",
    "SignalFilterChain",
    "SignalNormalizer",
    "SignalProcessor",
    "SignalRouter",
    "SignalScorer",
    "VoteSummary",
    "WeightedSignal",

    # registry / state
    "StrategyRegistry",
    "SignalState",
    "StrategyContextStore",
    "StrategyCooldownState",
    "StrategyMetricsState",
    "StrategyRuntimeState",

    # presets
    "ALL_STRATEGY_NAMES",
    "HYBRID_STRATEGIES",
    "INTRADAY_STRATEGIES",
    "LIQUIDITY_REVERSAL_STRATEGIES",
    "MEAN_REVERSION_STRATEGIES",
    "OPEN_INTEREST_STRATEGIES",
    "ORDERFLOW_STRATEGIES",
    "PRICE_ACTION_STRATEGIES",
    "SCALPING_STRATEGIES",
    "SPOOFING_STRATEGIES",
    "SPREADS_PRESET_STRATEGIES",
    "SPREADS_STRATEGIES",
    "STRATEGY_CATALOG",
    "SWING_STRATEGIES",
    "TREND_STACK_STRATEGIES",
    "WHALES_STRATEGIES",
    "StrategyCatalogEntry",
    "StrategyFactory",
    "StrategyNames",
    "StrategyPreset",
    "StrategyPresetBuilder",
    "Timeframes",
    "build_default_preset",
    "build_default_strategy_config",
    "build_default_strategy_registry",
    "build_intraday_preset",
    "build_liquidity_reversal_preset",
    "build_mean_reversion_preset",
    "build_preset_by_name",
    "build_scalping_preset",
    "build_spreads_preset",
    "build_swing_preset",
    "build_trend_stack_preset",
    "catalog_by_category",
    "configured_strategy_names",
    "enabled_strategy_names",
    "validate_strategy_catalog",

    # package metadata
    "__version__",
]