# trading_system/strategy/enums.py

from __future__ import annotations

from enum import Enum


class StrEnum(str, Enum):
    """
    Base enum that behaves as a stable lowercase string.

    Strategy package deliberately keeps its own enums instead of importing
    risk.enums directly. Cross-package conversion should happen only at the
    EventBus boundary when SignalProcessor/SignalRouter builds signal.generated
    payload for RiskManager.
    """

    def __str__(self) -> str:
        return self.value

    @classmethod
    def values(cls) -> tuple[str, ...]:
        return tuple(item.value for item in cls)

    @classmethod
    def has_value(cls, value: str) -> bool:
        return value in cls.values()

    @classmethod
    def safe_parse(cls, value: object, default: "StrEnum") -> "StrEnum":
        if isinstance(value, cls):
            return value
        if isinstance(value, str):
            try:
                return cls(value)
            except ValueError:
                return default
        return default


class SignalSide(StrEnum):
    """
    Strategy-side signal direction.

    Maps to risk PositionSide only when creating the signal.generated payload.
    FLAT/UNKNOWN must never be sent to RiskManager as an opening trade.
    """

    LONG = "long"
    SHORT = "short"
    FLAT = "flat"
    UNKNOWN = "unknown"

    @property
    def is_directional(self) -> bool:
        return self in {SignalSide.LONG, SignalSide.SHORT}

    @property
    def sign(self) -> int:
        if self is SignalSide.LONG:
            return 1
        if self is SignalSide.SHORT:
            return -1
        return 0


class SignalStatus(StrEnum):
    """
    Runtime lifecycle status of strategy signals.

    Risk/execution responses should update this state through StrategyEventHandler
    and SignalState, not by direct calls from risk/execution packages.
    """

    NEW = "new"
    PENDING = "pending"
    CONFIRMED = "confirmed"
    REJECTED = "rejected"
    CANCELLED = "cancelled"
    EXPIRED = "expired"
    EXECUTED = "executed"
    FAILED = "failed"

    @property
    def is_active(self) -> bool:
        return self in {
            SignalStatus.NEW,
            SignalStatus.PENDING,
            SignalStatus.CONFIRMED,
        }

    @property
    def is_terminal(self) -> bool:
        return self in {
            SignalStatus.REJECTED,
            SignalStatus.CANCELLED,
            SignalStatus.EXPIRED,
            SignalStatus.EXECUTED,
            SignalStatus.FAILED,
        }


class SetupType(StrEnum):
    """
    High-level setup family generated by concrete strategies.
    """

    REVERSAL = "reversal"
    CONTINUATION = "continuation"
    BREAKOUT = "breakout"
    MEAN_REVERSION = "mean_reversion"
    ARBITRAGE = "arbitrage"
    SQUEEZE = "squeeze"
    MOMENTUM = "momentum"
    ABSORPTION = "absorption"
    EXHAUSTION = "exhaustion"
    LIQUIDITY_SWEEP = "liquidity_sweep"
    STOP_HUNT = "stop_hunt"
    FVG_REACTION = "fvg_reaction"
    MARKET_STRUCTURE_SHIFT = "market_structure_shift"
    CVD_DIVERGENCE = "cvd_divergence"
    OI_CONFIRMATION = "oi_confirmation"
    FUNDING_EXTREME = "funding_extreme"
    WHALE_ABSORPTION = "whale_absorption"
    SPOOFING_TRAP = "spoofing_trap"
    BASIS_DISLOCATION = "basis_dislocation"
    HYBRID = "hybrid"
    UNKNOWN = "unknown"


class EntryType(StrEnum):
    """
    Strategy-side entry intent.

    This is not an execution order type. Execution is still responsible for
    translating the final risk-approved signal into exchange-specific orders.
    """

    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    PASSIVE = "passive"
    PULLBACK = "pullback"
    BREAKOUT_CONFIRMATION = "breakout_confirmation"
    TWAP = "twap"
    VWAP = "vwap"
    ICEBERG = "iceberg"


class ExitType(StrEnum):
    TAKE_PROFIT = "take_profit"
    STOP_LOSS = "stop_loss"
    TRAILING_STOP = "trailing_stop"
    TIME_EXIT = "time_exit"
    SIGNAL_FLIP = "signal_flip"
    INVALIDATION = "invalidation"
    MANUAL = "manual"
    PARTIAL = "partial"


class StrategyCategory(StrEnum):
    ORDERFLOW = "orderflow"
    LIQUIDITY = "liquidity"
    PRICE_ACTION = "price_action"
    LIQUIDATIONS = "liquidations"
    WHALES = "whales"
    SPOOFING = "spoofing"
    SPREADS = "spreads"
    FUNDING = "funding"
    OPEN_INTEREST = "open_interest"
    HYBRID = "hybrid"


class FeatureSource(StrEnum):
    """
    Source domain of normalized analytics features.
    """

    ORDERFLOW = "orderflow"
    LIQUIDITY = "liquidity"
    PRICE_ACTION = "price_action"
    LIQUIDATIONS = "liquidations"
    WHALES = "whales"
    SPOOFING = "spoofing"
    SPREADS = "spreads"
    FUNDING = "funding"
    OPEN_INTEREST = "open_interest"
    REGIME = "regime"
    PORTFOLIO = "portfolio"
    SYSTEM = "system"
    EXTERNAL = "external"

    @classmethod
    def from_strategy_category(cls, category: StrategyCategory) -> "FeatureSource":
        mapping: dict[StrategyCategory, FeatureSource] = {
            StrategyCategory.ORDERFLOW: cls.ORDERFLOW,
            StrategyCategory.LIQUIDITY: cls.LIQUIDITY,
            StrategyCategory.PRICE_ACTION: cls.PRICE_ACTION,
            StrategyCategory.LIQUIDATIONS: cls.LIQUIDATIONS,
            StrategyCategory.WHALES: cls.WHALES,
            StrategyCategory.SPOOFING: cls.SPOOFING,
            StrategyCategory.SPREADS: cls.SPREADS,
            StrategyCategory.FUNDING: cls.FUNDING,
            StrategyCategory.OPEN_INTEREST: cls.OPEN_INTEREST,
            StrategyCategory.HYBRID: cls.SYSTEM,
        }
        return mapping[category]


class MarketRegime(StrEnum):
    TRENDING_UP = "trending_up"
    TRENDING_DOWN = "trending_down"
    RANGING = "ranging"
    BREAKOUT = "breakout"
    SQUEEZE = "squeeze"
    HIGH_VOLATILITY = "high_volatility"
    LOW_VOLATILITY = "low_volatility"
    NEWS_DRIVEN = "news_driven"
    ILLIQUID = "illiquid"
    RISK_OFF = "risk_off"
    UNKNOWN = "unknown"

    @property
    def is_directional(self) -> bool:
        return self in {
            MarketRegime.TRENDING_UP,
            MarketRegime.TRENDING_DOWN,
            MarketRegime.BREAKOUT,
            MarketRegime.SQUEEZE,
        }

    @property
    def is_risky(self) -> bool:
        return self in {
            MarketRegime.HIGH_VOLATILITY,
            MarketRegime.NEWS_DRIVEN,
            MarketRegime.ILLIQUID,
            MarketRegime.RISK_OFF,
        }


class ConflictType(StrEnum):
    SIDE_CONFLICT = "side_conflict"
    REGIME_CONFLICT = "regime_conflict"
    FLOW_CONFLICT = "flow_conflict"
    EXECUTION_CONFLICT = "execution_conflict"
    FILTER_CONFLICT = "filter_conflict"
    TIMEFRAME_CONFLICT = "timeframe_conflict"
    PORTFOLIO_CONFLICT = "portfolio_conflict"
    CORRELATION_CONFLICT = "correlation_conflict"
    DUPLICATE_SIGNAL = "duplicate_signal"
    RISK_CONFLICT = "risk_conflict"


class ConfidenceGrade(StrEnum):
    VERY_LOW = "very_low"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    VERY_HIGH = "very_high"

    @property
    def rank(self) -> int:
        return {
            ConfidenceGrade.VERY_LOW: 1,
            ConfidenceGrade.LOW: 2,
            ConfidenceGrade.MEDIUM: 3,
            ConfidenceGrade.HIGH: 4,
            ConfidenceGrade.VERY_HIGH: 5,
        }[self]


class Timeframe(StrEnum):
    TICK = "tick"
    S1 = "1s"
    S5 = "5s"
    S15 = "15s"
    M1 = "1m"
    M3 = "3m"
    M5 = "5m"
    M15 = "15m"
    M30 = "30m"
    H1 = "1h"
    H4 = "4h"
    D1 = "1d"

    @property
    def seconds(self) -> int:
        return {
            Timeframe.TICK: 0,
            Timeframe.S1: 1,
            Timeframe.S5: 5,
            Timeframe.S15: 15,
            Timeframe.M1: 60,
            Timeframe.M3: 180,
            Timeframe.M5: 300,
            Timeframe.M15: 900,
            Timeframe.M30: 1800,
            Timeframe.H1: 3600,
            Timeframe.H4: 14400,
            Timeframe.D1: 86400,
        }[self]

    @property
    def is_intraday(self) -> bool:
        return self.seconds < 86400


class FilterDecision(StrEnum):
    PASS = "pass"
    WARN = "warn"
    BLOCK = "block"
    SKIP = "skip"

    @property
    def passed(self) -> bool:
        return self in {FilterDecision.PASS, FilterDecision.WARN}

    @property
    def blocked(self) -> bool:
        return self is FilterDecision.BLOCK


class SignalStrength(StrEnum):
    WEAK = "weak"
    MODERATE = "moderate"
    STRONG = "strong"
    EXTREME = "extreme"

    @property
    def rank(self) -> int:
        return {
            SignalStrength.WEAK: 1,
            SignalStrength.MODERATE: 2,
            SignalStrength.STRONG: 3,
            SignalStrength.EXTREME: 4,
        }[self]


class TriggerType(StrEnum):
    PRIMARY = "primary"
    CONFIRMATION = "confirmation"
    CONFLUENCE = "confluence"
    DERIVED = "derived"
    FILTERED = "filtered"


class SignalPriority(StrEnum):
    """
    Strategy-side priority for ordering and EventBus priority mapping.

    This is not risk tier. Risk tier is represented by StrategyTradeTier.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"

    @property
    def rank(self) -> int:
        return {
            SignalPriority.LOW: 1,
            SignalPriority.MEDIUM: 2,
            SignalPriority.HIGH: 3,
            SignalPriority.URGENT: 4,
        }[self]


class SignalOrigin(StrEnum):
    SINGLE_STRATEGY = "single_strategy"
    MULTI_STRATEGY = "multi_strategy"
    CONFLUENCE = "confluence"
    HYBRID = "hybrid"
    MANUAL = "manual"
    SYSTEM = "system"


class FreshnessStatus(StrEnum):
    FRESH = "fresh"
    AGING = "aging"
    STALE = "stale"
    EXPIRED = "expired"

    @property
    def usable(self) -> bool:
        return self in {FreshnessStatus.FRESH, FreshnessStatus.AGING}


class PresetMode(StrEnum):
    SCALPING = "scalping"
    INTRADAY = "intraday"
    SWING = "swing"


# ---------------------------------------------------------------------------
# Strategy-side aliases for risk-facing signal.generated payload
# ---------------------------------------------------------------------------
# These enums intentionally mirror values expected by risk.enums, but strategy
# does not import risk.enums. The conversion boundary is SignalProcessor /
# SignalRouter when building RiskReadySignalPayload.
# ---------------------------------------------------------------------------


class StrategyTradeTier(StrEnum):
    """
    Strategy-side suggested trade tier.

    Mirrors risk TradeTier values. Strategy may suggest a tier, but RiskManager
    may downgrade or reject it.
    """

    T1 = "t1"
    T2 = "t2"
    T3 = "t3"
    T4 = "t4"

    @property
    def rank(self) -> int:
        return {
            StrategyTradeTier.T1: 1,
            StrategyTradeTier.T2: 2,
            StrategyTradeTier.T3: 3,
            StrategyTradeTier.T4: 4,
        }[self]

    @classmethod
    def from_rank(cls, rank: int) -> "StrategyTradeTier":
        normalized = max(1, min(int(rank), 4))
        return {
            1: cls.T1,
            2: cls.T2,
            3: cls.T3,
            4: cls.T4,
        }[normalized]

    def downgrade(self, steps: int = 1) -> "StrategyTradeTier":
        return self.from_rank(self.rank - max(0, int(steps)))


class StrategyOrderIntent(StrEnum):
    """
    Strategy-side order intent.

    Mirrors risk OrderIntent values at the EventBus boundary.
    """

    OPEN = "open"
    INCREASE = "increase"
    REDUCE = "reduce"
    CLOSE = "close"
    FLIP = "flip"

    @property
    def increases_risk(self) -> bool:
        return self in {
            StrategyOrderIntent.OPEN,
            StrategyOrderIntent.INCREASE,
            StrategyOrderIntent.FLIP,
        }

    @property
    def reduces_risk(self) -> bool:
        return self in {
            StrategyOrderIntent.REDUCE,
            StrategyOrderIntent.CLOSE,
        }


class StrategyLiquidityClass(StrEnum):
    """
    Strategy-side liquidity class suggestion.

    Mirrors risk LiquidityClass values. Should be derived from analytics/context,
    not hardcoded inside concrete strategies when possible.
    """

    TOP = "top"
    HIGH = "high"
    NORMAL = "normal"
    LOW = "low"
    ILLIQUID = "illiquid"
    SHITCOIN = "shitcoin"

    @property
    def is_high_quality(self) -> bool:
        return self in {
            StrategyLiquidityClass.TOP,
            StrategyLiquidityClass.HIGH,
        }

    @property
    def is_risky(self) -> bool:
        return self in {
            StrategyLiquidityClass.LOW,
            StrategyLiquidityClass.ILLIQUID,
            StrategyLiquidityClass.SHITCOIN,
        }


class StrategyExecutionQuality(StrEnum):
    """
    Strategy-side execution quality estimate.

    Mirrors risk ExecutionQuality values. Final execution checks still belong
    to risk/execution layers.
    """

    EXCELLENT = "excellent"
    GOOD = "good"
    ACCEPTABLE = "acceptable"
    POOR = "poor"
    BLOCKED = "blocked"

    @property
    def is_tradeable(self) -> bool:
        return self in {
            StrategyExecutionQuality.EXCELLENT,
            StrategyExecutionQuality.GOOD,
            StrategyExecutionQuality.ACCEPTABLE,
        }


class StrategyMarginMode(StrEnum):
    """
    Futures margin mode suggestion.

    Mirrors risk MarginMode values. Default should normally be ISOLATED for
    strategy-generated futures/perpetual signals unless explicitly configured.
    """

    ISOLATED = "isolated"
    CROSS = "cross"


class StrategyMarketType(StrEnum):
    """
    Futures/perpetual-focused market type.

    Strategy package is currently futures-first. Spot should not be used unless
    explicitly requested in a future architecture change.
    """

    USDM_FUTURES = "usdm_futures"
    COINM_FUTURES = "coinm_futures"
    LINEAR = "linear"
    INVERSE = "inverse"
    SWAP = "swap"
    PERPETUAL = "perpetual"

    @property
    def is_futures(self) -> bool:
        return True


class RiskPayloadField(StrEnum):
    """
    Stable keys used by SignalProcessor/SignalRouter when building the
    signal.generated payload consumed by RiskManager.
    """

    SIGNAL_ID = "signal_id"
    SYMBOL = "symbol"
    SIDE = "side"

    ENTRY_PRICE = "entry_price"
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"

    STRATEGY_NAME = "strategy_name"
    TIER = "tier"
    ORDER_INTENT = "order_intent"

    CONFIDENCE = "confidence"
    EDGE_SCORE = "edge_score"
    PRIORITY_SCORE = "priority_score"
    VOLATILITY = "volatility"

    LIQUIDITY_CLASS = "liquidity_class"
    EXECUTION_QUALITY = "execution_quality"

    EXPECTED_REWARD = "expected_reward"
    EXPECTED_LOSS = "expected_loss"
    EXPECTED_WIN_PROBABILITY = "expected_win_probability"
    EXPECTED_COST = "expected_cost"

    REQUESTED_SIZE = "requested_size"
    REQUESTED_MARGIN = "requested_margin"
    REQUESTED_LEVERAGE = "requested_leverage"

    REDUCE_ONLY = "reduce_only"
    MARGIN_MODE = "margin_mode"

    EXCHANGE = "exchange"
    MARKET_TYPE = "market_type"
    TIMEFRAME = "timeframe"

    TIMESTAMP = "timestamp"
    METADATA = "metadata"


__all__ = [
    "StrEnum",
    "SignalSide",
    "SignalStatus",
    "SetupType",
    "EntryType",
    "ExitType",
    "StrategyCategory",
    "FeatureSource",
    "MarketRegime",
    "ConflictType",
    "ConfidenceGrade",
    "Timeframe",
    "FilterDecision",
    "SignalStrength",
    "TriggerType",
    "SignalPriority",
    "SignalOrigin",
    "FreshnessStatus",
    "PresetMode",
    "StrategyTradeTier",
    "StrategyOrderIntent",
    "StrategyLiquidityClass",
    "StrategyExecutionQuality",
    "StrategyMarginMode",
    "StrategyMarketType",
    "RiskPayloadField",
]